# 基础镜像
FROM cbs-acr-shanghai-registry.cn-shanghai.cr.aliyuncs.com/ns-shanghai/cbs-acr-shanghai:nginx-latest
# author
MAINTAINER cbs
# 解决docker控制台打印日期时区不对的问题
# 设置环境变量TZ为Asia/Shanghai
ENV TIME_ZONE=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime
# 挂载目录
VOLUME /home/cbs/projects/legaldb-ui
# 创建目录
RUN mkdir -p /home/cbs/projects/legaldb-ui
# 指定路径
WORKDIR /home/cbs/projects/legaldb-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/cbs/projects/legaldb-ui
