# 基础镜像
FROM cbs-acr-shanghai-registry.cn-shanghai.cr.aliyuncs.com/ns-shanghai/cbs-acr-shanghai:nginx-latest
# author
MAINTAINER cbs
# # 解决docker控制台打印日期不准确问题
# # 设置环境变量TZ，指定时区
# ENV TZ=Asia/Shanghai
#
# # 安装时区数据，并链接到/etc/localtime
# RUN apt-get update && \
#     apt-get install -y tzdata && \
#     ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
#     echo $TZ > /etc/timezone && \
#     dpkg-reconfigure -f noninteractive tzdata && \
#     rm -rf /var/lib/apt/lists/*
# 解决docker控制台打印日期时区不对的问题
# 设置环境变量TZ为Asia/Shanghai
ENV TIME_ZONE=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime
# 挂载目录
VOLUME /home/cbs/projects/sysmgmt-ui
# 创建目录
RUN mkdir -p /home/cbs/projects/sysmgmt-ui
# 指定路径
WORKDIR /home/cbs/projects/sysmgmt-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/cbs/projects/sysmgmt-ui
